name: Build for release

on:
  push:
    paths:
      - ".github/workflows/Build for release.yml"
  pull_request:
    paths:
      - ".github/workflows/Build for release.yml"
  release:
    types: [published]
  schedule:
    - cron: "0 0 1 * *" # 1st of every month at 8 AM CST

env:
  Executable: mockgpt

jobs:
  publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Create file1.txt
        run: echo "This is file 1" > file1.txt

      - name: Create file2.txt
        run: echo "This is file 2" > file2.txt

      - name: Show assets
        run: |
          ls

      - name: Publish to Releases
        uses: ncipollo/release-action@v1
        with:
          name: "MockGPT v${{ github.event.release.tag_name }}"
          allowUpdates: true
          artifactErrorsFailBuild: false
          artifacts: "file1.txt,file2.txt"
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
