name: Crystal CI

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
  schedule:
    - cron: "0 0 * * 1" # Every Monday 8 AM CST

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        crystal: [latest, nightly]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --order=random
      - name: Build
        run: shards build

  compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.4.1
      - name: Specify shards version
        run: |
          sed -i '/github: grip-framework\/grip/a \ \ \ \ version: 2.0.1' shard.yml
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --order=random
      - name: Build
        run: shards build
